### ISSUE TITLE
Completion message was too quick to read

### ISSUE THREAD

**Issue by smambrose** [noahslocum/CSTC_BadFieldNameFixer#1]
@noahslocum 

When I ran the tool the "success" message popped up, but the UI closed too quickly to read it. Is there a way we can delay the time for the program to close?

**Comment by noahslocum** [comment]
This shouldn't be an issue if users run the script in an IDE, but I suppose it's expected that some will run the script without bringing it into an IDE first.
I can have the script prompt users to press ENTER to close the program, this should solve the problem.

**Comment by smambrose** [comment]
Agreed - that sounds good. The way I read the instructions I figured you mean just double click - which is what I did (FYI could not copy and paste, but that's ok).

**Comment by noahslocum** [comment]
Implemented with: https://github.com/noahslocum/CSTC_BadFieldNameFixer/commit/8b56d312ef19ed023b11a90232730d7a07981b4d
